### ISSUE TITLE
Role "LIV_SONAR_QUBE" does not exist.

### ISSUE THREAD

**Issue by giovannabarbosamg** [SonarSource/helm-chart-sonarqube#119]
hello, I have been trying to upload a sonarqube on ibm supported kubernetes and get the error described in the title. 
my values.yaml:
```
fullnameOverride: sonarqube-homolog  
  chart: sonarqube
  chartVersion: 1.2.0
  release: sonarqube-homolog
  namespace: sonarqube
  repo: https://SonarSource.github.io/helm-chart-sonarqube
image:
  repository: sonarqube
  tag: 7.8-community-oracle
# Set security context for sonarqube pod
# securityContext:
#   fsGroup: 0

# # Set security context for sonarqube container
# containerSecurityContext:
#   # Sonarqube dockerfile creates sonarqube user as UID and GID 1000
#   runAsUser: 0
ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    nginx.org/redirect-to-https: "True"
    nginx.org/client-max-body-size: "0m"
    nginx.ingress.kubernetes.io/proxy-body-size: "0m"
  enabled: true
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 20Gi
  storageClass: ibmc-file-retain-gold

jdbcOverwrite:
  enable: false
  jdbcUrl: "jdbc:postgresql://sonarqube-homolog-postgresql/sonarDB?socketTimeout=1500"
  jdbcUsername: "LIV_SONAR_QUBE"
  jdbcPassword: "sonarPass"

postgresql:
  enabled: true
  postgresqlUsername: "LIV_SONAR_QUBE"
  postgresqlPassword: "sonarPass"
  postgresqlDatabase: "sonarDB"
  persistence:
    storageClass: ibmc-file-retain-gold
  securityContext:
    enabled: true
    fsGroup: 0
  containerSecurityContext:
    enabled: true
    runAsUser: 0

prometheusExporter:
  enabled: false

replicaCount: 1
resources:
  limits:
    cpu: "2"
    memory: 3Gi
  requests:
    cpu: 50m
    memory: 2G
service:
  type: ClusterIP
sonarProperties:
  sonar.jdbc.password: sonarPass
  sonar.jdbc.url: jdbc:postgresql://sonarqube-homolog-postgresql:5432/sonarDB
  sonar.jdbc.username: LIV_SONAR_QUBE

```
postgresql pod logs:
```
[38;5;6mpostgresql [38;5;5m19:07:28.09 [0m
[38;5;6mpostgresql [38;5;5m19:07:28.09 [0m[1mWelcome to the Bitnami postgresql container[0m
[38;5;6mpostgresql [38;5;5m19:07:28.10 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-postgresql[0m
[38;5;6mpostgresql [38;5;5m19:07:28.10 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-postgresql/issues[0m
[38;5;6mpostgresql [38;5;5m19:07:28.10 [0m
[38;5;6mpostgresql [38;5;5m19:07:28.10 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL setup **
[38;5;6mpostgresql [38;5;5m19:07:28.13 [0m[38;5;2mINFO [0m ==> Validating settings in POSTGRESQL_* env vars..
[38;5;6mpostgresql [38;5;5m19:07:28.21 [0m[38;5;2mINFO [0m ==> Loading custom pre-init scripts...
[38;5;6mpostgresql [38;5;5m19:07:28.21 [0m[38;5;2mINFO [0m ==> Initializing PostgreSQL database...
[38;5;6mpostgresql [38;5;5m19:07:34.15 [0m[38;5;2mINFO [0m ==> pg_hba.conf file not detected. Generating it...
[38;5;6mpostgresql [38;5;5m19:07:34.15 [0m[38;5;2mINFO [0m ==> Generating local authentication configuration
[38;5;6mpostgresql [38;5;5m19:07:34.16 [0m[38;5;2mINFO [0m ==> Deploying PostgreSQL with persisted data...
[38;5;6mpostgresql [38;5;5m19:07:34.18 [0m[38;5;2mINFO [0m ==> Configuring replication parameters
[38;5;6mpostgresql [38;5;5m19:07:34.21 [0m[38;5;2mINFO [0m ==> Configuring fsync
[38;5;6mpostgresql [38;5;5m19:07:34.25 [0m[38;5;2mINFO [0m ==> Loading custom scripts...
[38;5;6mpostgresql [38;5;5m19:07:34.26 [0m[38;5;2mINFO [0m ==> Enabling remote connections

[38;5;6mpostgresql [38;5;5m19:07:34.27 [0m[38;5;2mINFO [0m ==> ** PostgreSQL setup finished! **
[38;5;6mpostgresql [38;5;5m19:07:34.30 [0m[38;5;2mINFO [0m ==> ** Starting PostgreSQL **
2021-11-22 19:07:34.336 GMT [1] LOG:  pgaudit extension initialized
2021-11-22 19:07:34.336 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-11-22 19:07:34.336 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-11-22 19:07:34.360 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-11-22 19:07:34.728 GMT [134] LOG:  database system was shut down at 2021-11-22 19:05:07 GMT
2021-11-22 19:07:35.089 GMT [1] LOG:  database system is ready to accept connections
2021-11-22 19:07:36.426 GMT [147] FATAL:  password authentication failed for user "LIV_SONAR_QUBE"
2021-11-22 19:07:36.426 GMT [147] DETAIL:  Role "LIV_SONAR_QUBE" does not exist.

```

sonarqube-homolog pod logs:
```

2021.11.22 19:14:55 WARN  app[][o.s.application.App] SonarQube will require Java 11+ starting on next version
2021.11.22 19:14:55 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2021.11.22 19:14:55 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2021.11.22 19:14:56 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2021.11.22 19:14:56 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2021.11.22 19:14:56 INFO  app[][o.e.p.PluginsService] no modules loaded
2021.11.22 19:14:56 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2021.11.22 19:15:10 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2021.11.22 19:15:10 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/local/openjdk-8/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process1910771622079035720properties
2021.11.22 19:15:10 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2021.11.22 19:15:11 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2021.11.22 19:15:12 INFO  web[][o.e.p.PluginsService] no modules loaded
2021.11.22 19:15:12 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2021.11.22 19:15:12 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2021.11.22 19:15:12 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2021.11.22 19:15:14 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2021.11.22 19:15:14 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 7.8.0.26217 / daf4da5c554d4153a11e68d13a662313e6cecc92
2021.11.22 19:15:14 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Starting embedded database on port 9092 with url jdbc:h2:tcp://127.0.0.1:9092/sonar
2021.11.22 19:15:14 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database started. Data stored in: /opt/sonarqube/data
2021.11.22 19:15:14 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:9092/sonar
2021.11.22 19:15:15 WARN  web[][o.s.db.dialect.H2] H2 database should be used for evaluation purpose only.
2021.11.22 19:15:16 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2021.11.22 19:15:16 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2021.11.22 19:15:16 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@4a760e24 [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/properties*, ...]}]
2021.11.22 19:15:17 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2021.11.22 19:15:18 INFO  web[][o.s.s.p.UpdateCenterClient] Update center: https://update.sonarsource.org/update-center.properties (no proxy)
2021.11.22 19:15:18 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Unable to load component class org.sonar.server.platform.ws.SystemWs
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
	at org.picocontainer.parameters.CollectionComponentParameter.getArrayInstance(CollectionComponentParameter.java:334)
	at org.picocontainer.parameters.CollectionComponentParameter.access$100(CollectionComponentParameter.java:49)
	at org.picocontainer.parameters.CollectionComponentParameter$1.resolveInstance(CollectionComponentParameter.java:139)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:141)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:561)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.server.platform.ws.InfoAction
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
	at org.picocontainer.parameters.CollectionComponentParameter.getArrayInstance(CollectionComponentParameter.java:334)
	at org.picocontainer.parameters.CollectionComponentParameter.access$100(CollectionComponentParameter.java:49)
	at org.picocontainer.parameters.CollectionComponentParameter$1.resolveInstance(CollectionComponentParameter.java:139)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:141)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:63)
	... 28 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.server.platform.ws.StandaloneSystemInfoWriter
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:63)
	... 44 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.server.platform.monitoring.StandaloneSystemSection
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
	at org.picocontainer.parameters.CollectionComponentParameter.getArrayInstance(CollectionComponentParameter.java:334)
	at org.picocontainer.parameters.CollectionComponentParameter.access$100(CollectionComponentParameter.java:49)
	at org.picocontainer.parameters.CollectionComponentParameter$1.resolveInstance(CollectionComponentParameter.java:139)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:141)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:63)
	... 58 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.server.user.SecurityRealmFactory
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:63)
	... 74 common frames omitted
Caused by: org.sonar.api.utils.SonarException: Realm 'LDAP' not found. Please check the property 'sonar.security.realm' in conf/sonar.properties
	at org.sonar.server.user.SecurityRealmFactory.<init>(SecurityRealmFactory.java:54)
	at org.sonar.server.user.SecurityRealmFactory.<init>(SecurityRealmFactory.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:63)
	... 88 common frames omitted
2021.11.22 19:15:18 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2021.11.22 19:15:18 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
2021.11.22 19:15:18 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2021.11.22 19:15:18 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2021.11.22 19:15:18 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2021.11.22 19:15:18 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

```

help me please

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @giovannabarbosamg 

>    tag: 7.8-community-oracle

The earliest supported version of sonarqube by this helm chart is 8.9 (LTS chart). 7.8 is already EOL and you should upgrade to the current LTS (8.9) or the latest release (9.2 as of time of writing).

**Comment by giovannabarbosamg** [comment]
hi @tobias-trabelsi-sonarsource !
what is the helm chart that supports this version of sonarquebe?

**Comment by tobias-trabelsi-sonarsource** [comment]
There is none. Official kubernetes support was brought up with SonarQube 8.9

**Comment by tobias-trabelsi-sonarsource** [comment]
Closing due to inactivity
