### ISSUE TITLE
Installing sonar using the helm chart gives a PostgresSQL user does not exist error

### ISSUE THREAD

**Issue by alisaleemh** [SonarSource/helm-chart-sonarqube#46]
Hi @tobias-trabelsi-sonarsource - I tried installing the helm chart but I get the following error in postgresql pod

```
2021-07-05 20:46:03.964 GMT [1341] FATAL:  password authentication failed for user "sonarUser"
2021-07-05 20:46:03.964 GMT [1341] DETAIL:  Role "sonarUser" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

This is the error that appears in the sonarqube pod log:

```java.lang.IllegalStateException: Fail to connect to database
	at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:86)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel1.start(PlatformLevel1.java:166)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel1Container(PlatformImpl.java:172)
	at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:86)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4705)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5171)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').
	at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:118)
	at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:83)
	... 24 common frames omitted
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "sonarUser")
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at org.sonar.db.profiling.NullConnectionInterceptor.getConnection(NullConnectionInterceptor.java:31)
	at org.sonar.db.profiling.ProfiledDataSource.getConnection(ProfiledDataSource.java:317)
	at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:115)
	... 25 common frames omitted
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "sonarUser"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:613)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.connect(Driver.java:264)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665)
	... 30 common frames omitted
2021.07.05 20:43:50 WARN  web[][o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [pool-3-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:\n java.base@11.0.11/sun.nio.ch.EPoll.wait(Native Method)\n java.base@11.0.11/sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)\n java.base@11.0.11/sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)\n java.base@11.0.11/sun.nio.ch.SelectorImpl.select(Unknown Source)\n app//org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:343)\n app//org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)\n app//org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)\n java.base@11.0.11/java.lang.Thread.run(Unknown Source)
2021.07.05 20:43:50 WARN  web[][o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [I/O dispatcher 1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:\n java.base@11.0.11/sun.nio.ch.EPoll.wait(Native Method)\n java.base@11.0.11/sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)\n java.base@11.0.11/sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)\n java.base@11.0.11/sun.nio.ch.SelectorImpl.select(Unknown Source)\n app//org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)\n app//org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)\n app//org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)\n java.base@11.0.11/java.lang.Thread.run(Unknown Source)
2021.07.05 20:43:50 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
```

It appears that the user was not created in the postgressql database. I tried manually adding a pg_hba.conf file and changed the auth method to `password` from `md5`, but it does not work. 

Any ideas on how to solve it? Thanks.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @alisaleemh ,

are you using the default values or did you do any modifications? i can not reproduce this on my side. which version of the bitnami helm chart for postgres did you use?

**Comment by alisaleemh** [comment]
Hi @tobias-trabelsi-sonarsource, thanks for responding. The only value I changed is setting volumePermissions=enabled.

```
   volumePermissions:
     # For standard Kubernetes deployment, set enabled=false
     # For OpenShift, set enabled=true and ensure to set volumepermissions.securitycontext.runAsUser below.
-    enabled: false
+    enabled: true
```

The postgres chart version is `8.6.4`

**Comment by tobias-trabelsi-sonarsource** [comment]
How did you deploy? did you modify the `values.yaml` in this repo or just defined the values that you want to overwrite?
i just bootstraped a new cluster and tried to reproduce this but everything is rendered correctly on my side.

```bash
kubectl create ns test-ce
helm upgrade --install -f values.yaml -n test-ce test-ce ./
kubectl get pods -n test-ce -w
NAME                   READY   STATUS              RESTARTS   AGE
test-ce-postgresql-0   0/1     ContainerCreating   0          7s
test-ce-sonarqube-0    0/1     Init:0/3            0          7s
test-ce-postgresql-0   0/1     Running             0          39s
test-ce-postgresql-0   1/1     Running             0          53s
test-ce-sonarqube-0    0/1     Init:1/3            0          54s
test-ce-sonarqube-0    0/1     Init:2/3            0          55s
test-ce-sonarqube-0    0/1     PodInitializing     0          58s
test-ce-sonarqube-0    0/1     Running             0          77s
```

**Comment by alisaleemh** [comment]
@tobias-trabelsi-sonarsource I modified the `values.yaml` and installed the same way you did. FYI - my cluster is provisioned in the IBM Cloud Kubernetes service. 

```
kubectl create namespace sonarqube
helm upgrade --install -f values.yaml -n sonarqube sonarqube ./
```

I get log messages in the `posgressql-sonarqube-0` pod that the role sonarUser does not exist. Which means postgres failed to create the user. 

```
021-07-07 13:54:13.980 GMT [218998] DETAIL:  Role "sonarUser" does not exist.
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hmm i don't have any experience with the IBM cloud, so i don't know. in any case, can you validate that the bitnami helm chart is working for you? because in the end we just define it as a dependency and define the values for this helm chart.

what you could also do is to check if the following environment variables are present in the postgresql pod:

* POSTGRES_PASSWORD
* POSTGRES_USER
* POSTGRES_DB

**Comment by alisaleemh** [comment]
@tobias-trabelsi-sonarsource yes, the env vars are correctly set:

```
postgresql@sonarqube-postgresql-0:/$ echo $POSTGRES_DB
sonarDB
postgresql@sonarqube-postgresql-0:/$ echo $POSTGRES_USER
sonarUser
```

I however fail to login to psql CLI, which is perhaps due to the fact that the pg_hba.conf file has the auth method is `md5` and not `password`.

How can I validate the postgres chart is working?

**Comment by tobias-trabelsi-sonarsource** [comment]
You take the bitnami helm chart and deploy it separately in the same namespace as sonarqube. after that you set `postgresql.enabled=false`, set `postgresql.postgresqlUsername`, `postgresql.postgresqlPassword` and `postgresql.postgresqlDatabase` to match the configuration from the bitnami deployment and at last define `jdbcUrlOverride` to the jdbc url that is computed from the bitnami deployment. basically doing what this helm chart does manually. 

the configuration of the authentication mechanism for the database is controlled by the dependent helm chart as well, so i don't think there is a an issue in the auth method.

**Comment by JustFrt** [comment]
Hi,
I had the same issue and worked around it by increasing the postgres `livenessProbe` and `readinessProbe` `initialDelaySeconds` to 60.

```yaml
postgresql:
  livenessProbe:
    initialDelaySeconds: 60
  readinessProbe:
    initialDelaySeconds: 60
```

For me it most likely it was related to the NFS storage not being fast enough and the postgres setup some how skipping the user creation.

**Comment by tobias-trabelsi-sonarsource** [comment]
closing due to inactivity
